# Generated by Django 4.1.2 on 2022-10-22 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='products/%Y', verbose_name='Картинка товара')),
                ('description', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('available', models.BooleanField(default=True)),
                ('diagonal', models.CharField(max_length=200, verbose_name='Диагональ')),
                ('smart_tv', models.BooleanField(default=True)),
                ('release', models.DateTimeField(verbose_name='Выпуск на рынок')),
                ('resolution', models.CharField(max_length=200, verbose_name='Разрешение экрана')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Телевизор',
                'verbose_name_plural': 'Телевизоры',
            },
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='products/%Y', verbose_name='Картинка товара')),
                ('description', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('available', models.BooleanField(default=True)),
                ('age', models.IntegerField(verbose_name='Возвраст')),
                ('material', models.CharField(max_length=100, verbose_name='Материал игрушки')),
                ('release', models.DateTimeField(verbose_name='Выпуск на рынок')),
                ('country', models.CharField(max_length=30, verbose_name='Страна происхождения')),
                ('company', models.CharField(max_length=30, verbose_name='Фирма')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Игрушка',
                'verbose_name_plural': 'Игрушки',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='products/%Y', verbose_name='Картинка товара')),
                ('description', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('available', models.BooleanField(default=True)),
                ('kind_of_sport', models.CharField(max_length=200, verbose_name='Вид спорта')),
                ('material', models.CharField(max_length=100, verbose_name='Материал товара')),
                ('colour', models.CharField(max_length=25, verbose_name='Цвет товара')),
                ('country', models.CharField(max_length=30, verbose_name='Страна происхождения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Спортивный товар',
                'verbose_name_plural': 'Спортивные товары',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='products/%Y', verbose_name='Картинка товара')),
                ('description', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('available', models.BooleanField(default=True)),
                ('company', models.CharField(max_length=30, verbose_name='Фирма')),
                ('country', models.CharField(max_length=30, verbose_name='Страна происхождения')),
                ('sex', models.CharField(max_length=10, verbose_name='Пол')),
                ('size', models.IntegerField(verbose_name='Размер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
            },
        ),
    ]
