# Generated by Django 4.1.2 on 2022-10-23 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_imageproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSportProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_product/%Y', verbose_name='Картинка товара')),
                ('sport_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_product', to='product_app.sport')),
            ],
            options={
                'verbose_name': 'Картинка товара',
                'verbose_name_plural': 'Картинки товаров',
            },
        ),
        migrations.DeleteModel(
            name='ImageProducts',
        ),
    ]
