# Generated by Django 4.1.2 on 2022-10-23 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
        ('order_app', '0002_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart_app.cart', verbose_name='Корзина'),
        ),
    ]
