# Generated by Django 4.1.2 on 2022-10-23 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_remove_profile_orders'),
        ('order_app', '0003_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='profile_app.profile', verbose_name='Покупатель'),
        ),
    ]
