# Generated by Django 4.1.2 on 2022-10-23 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_profile_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='orders',
        ),
    ]
